local o = vim.opt


o.autoindent     = true -- enable autoindent
o.clipboard      = "unnamedplus" -- uses system clipboard by default
o.autoread       = true
o.autowrite      = true -- auto write buffer when it's not focused
o.cursorline     = true -- enable cursor line
o.encoding       = "utf-8"
o.expandtab      = true -- use spaces instead of tabs
o.foldlevelstart = 20 
o.foldmethod     = "indent"
o.foldnestmax    = 3 -- deepest fold ist 3 levels
o.gcr            = "a:blinkon0"
o.hidden         = true
o.history        = 1000
o.hlsearch       = true -- highlight search 
o.ignorecase     = true -- case insensitive 
o.incsearch      = true -- incremental search
o.lazyredraw     = true
o.linebreak      = true -- Wrap lines at convenient points
o.magic          = true -- For regular expressions turn magic on
o.mat            = 2    -- How many tenths of a second to blink when matching brackets
o.number         = true
o.pumheight      = 10 -- limit completion items
o.relativenumber = false
o.ruler          = true
o.scrolloff      = 8	  -- Start scrolling when we're 8 lines away from margins
o.shell          = "/bin/zsh"
o.shiftwidth     = 2    -- width for autoindents
o.showcmd        = true
o.showmatch      = true -- show matching 
o.showmode       = true
o.sidescroll     = 1
o.sidescrolloff  = 15
o.smartcase      = true	-- unless we type a capital
o.smartindent    = true
o.smartindent    = true -- smarter indentation
o.smarttab       = true
o.softtabstop    = 2    -- see multiple spaces as tabstops so <BS> does the right thing
o.tabstop        = 2    -- number of columns occupied by a tab 
o.ttyfast        = true -- Speed up scrolling in Vim
o.visualbell     = true
o.wildmenu       = true
o.wildmode       = "longest,list"  -- get bash-like tab completions
